apiVersion: v1
kind: Pod
metadata:
  labels:
    app: caddy
  name: caddy
spec:
  hostNetwork: true
  containers:
    - name: caddy
      image: caddy:latest
      volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
        - name: caddy-data
          mountPath: /data
  volumes:
    - name: caddyfile
      hostPath:
        path: ./Caddyfile
    - name: caddy-data
      persistentVolumeClaim:
        claimName: caddy-data-pvc