apiVersion: v1
kind: Pod
metadata:
  labels:
    app: droneci
  name: droneci
spec:
  containers:
    - name: drone-server
      image: drone/drone:2
      env:
        - name: DRONE_GITEA_SERVER
          value: http://gitea:3000
        - name: DRONE_GITEA_CLIENT_ID
          value: your-gitea-client-id
        - name: DRONE_GITEA_CLIENT_SECRET
          value: your-gitea-client-secret
        - name: DRONE_RPC_SECRET
          value: super-duper-secret
        - name: DRONE_SERVER_HOST
          value: drone.example.com
        - name: DRONE_SERVER_PROTO
          value: http
      volumeMounts:
        - name: drone-data
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
      ports:
        - containerPort: 80
          hostPort: 8080
    - name: drone-runner
      image: drone/drone-runner-docker:1
      env:
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_HOST
          value: localhost
        - name: DRONE_RPC_SECRET
          value: super-duper-secret
        - name: DRONE_RUNNER_CAPACITY
          value: "2"
        - name: DRONE_RUNNER_NAME
          value: my-first-runner
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: drone-data
      persistentVolumeClaim:
        claimName: drone-data-pvc
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
