services:
  mosquitto:
    image: eclipse-mosquitto:${IMAGE_VERSION}
    container_name: mosquitto
    ports:
      - "${TCP_PORT}:1883"
      - "${WS_PORT}:9001"
    volumes:
      - data:/mosquitto/data
      - log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: always
volumes:
  data:
    driver: local
  log:
    driver: local
