apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  containers:
    - name: mosquitto
      image: eclipse-mosquitto:2
      volumeMounts:
        - name: data
          mountPath: /mosquitto/data
        - name: log
          mountPath: /mosquitto/log
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          readOnly: true
      ports:
        - containerPort: 1883
          hostPort: 1883
        - containerPort: 9001
          hostPort: 9001
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mosquitto-data-pvc
    - name: log
      persistentVolumeClaim:
        claimName: mosquitto-log-pvc
    - name: config
      hostPath:
        path: ./mosquitto.conf