apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  containers:
    - name: pgadmin
      image: dpage/pgadmin4:latest
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: root
      volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      ports:
        - containerPort: 80
          hostPort: 5050
  volumes:
    - name: pgadmin-data
      persistentVolumeClaim:
        claimName: pgadmin-data-pvc