apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mattermost
  name: mattermost-pod
spec:
  containers:
  - name: db
    image: docker.io/library/postgres:${POSTGRES_IMAGE_VERSION}
    env:
    - name: POSTGRES_USER
      value: ${DB_USER}
    - name: POSTGRES_PASSWORD
      value: ${DB_PASSWORD}
    - name: POSTGRES_DB
      value: ${DB_NAME}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-data

  - name: mattermost
    image: docker.io/mattermost/mattermost-team-edition:${IMAGE_VERSION}
    env:
    - name: MM_SQLSETTINGS_DRIVERNAME
      value: postgres
    - name: MM_SQLSETTINGS_DATASOURCE
      value: postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}?sslmode=disable&connect_timeout=10
    - name: MM_SERVICESETTINGS_SITEURL
      value: ${SITE_URL}
    ports:
    - containerPort: 8065
      hostPort: ${PORT}
      protocol: TCP
    volumeMounts:
    - mountPath: /mattermost/data
      name: mattermost-data
    - mountPath: /mattermost/config
      name: mattermost-config
    - mountPath: /mattermost/logs
      name: mattermost-logs
    - mountPath: /mattermost/plugins
      name: mattermost-plugins

  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: mattermost-data
    persistentVolumeClaim:
      claimName: mattermost-data-pvc
  - name: mattermost-config
    persistentVolumeClaim:
      claimName: mattermost-config-pvc
  - name: mattermost-logs
    persistentVolumeClaim:
      claimName: mattermost-logs-pvc
  - name: mattermost-plugins
    persistentVolumeClaim:
      claimName: mattermost-plugins-pvc
