apiVersion: v1
kind: Pod
metadata:
  labels:
    app: agent-zero
  name: agent-zero-pod
spec:
  containers:
    - name: agent-zero
      image: docker.io/agent0ai/agent-zero:${IMAGE_VERSION}
      env:
        - name: TZ
          value: ${TZ}
      ports:
        - containerPort: 80
          hostPort: ${PORT}
          protocol: TCP
      volumeMounts:
        - mountPath: /a0/usr
          name: agent-zero-data
        - mountPath: /etc/timezone
          name: timezone
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true

  volumes:
    - name: agent-zero-data
      persistentVolumeClaim:
        claimName: agent-zero-data-pvc
    - name: timezone
      hostPath:
        path: /etc/timezone
    - name: localtime
      hostPath:
        path: /etc/localtime
